### ISSUE TITLE
Class methods

### ISSUE THREAD

**Issue by bonafernando** [mckomo/metaxa#1]
How do I use like the example below with _local_method_variable_ being local method variable?

```
class Calculation

  include Metaxa

  def self.salary(params)
      introduce :local_method_variable, with_value: Time.now
      local_method_variable
  end

end
```

Thank you!!

**Comment by mckomo** [comment]
@bonafernando thank you for investing your time in my little project. Sadly **metaxa** version 0.1.0 does not support static context. However I have decided to add this feature and today I have released version 0.1.1. You can install newest version with command: 

```bash
gem install metaxa -v 0.1.1
```

If you added **metaxa** to your Gemspec you should specify at least version 0.1. Now if you done with gem update, change `include` to `extend`. This change is required because you are working in static context and you need to be able to reach `introduce` method from this context. Finally your example should look like this:

```ruby
class Calculation

  extend Metaxa

  def self.salary(params)
      introduce :local_method_variable, with_value: Time.now
      local_method_variable
  end

end
```

I have added some new [tests](https://github.com/mckomo/metaxa/tree/master/test) and [examples](https://github.com/mckomo/metaxa/tree/master/examples). I encourage you to look into that.
